<div class="body5">
    <div class="body6">
        <div class="main">
            <div class="wrapper">
                <figure class="left"><img src="images/letter3.png" alt=""></figure>
                <h2>What We Can Do <span>For Your</span></h2>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.
            </div>
        </div>
    </div>
</div>
<div class="body7">
    <div class="main">
        <section id="content">
            <div class="wrapper">
                <article class="col2">
                    <div class="pad1">
                        <h2>Our Services</h2>
                    </div>
                    <div class="box2">
                        <div class="box2_top">
                            <div class="box2_bot">
                                <div class="pad">
                                    <div class="wrapper">
                                        <figure class="left"><img src="images/marker_1.gif" alt=""></figure>
                                        <div class="cols">
                                            <a href="#">Nemo enim ipsam voluptatem quia voluptas sit aspernatur</a>
                                            Sed quia consequuntur magni dolores eosqui ratione voluptatem sequi nes ciunt. Neque porro quisiquam est, qui dolorem ipsum quia doloirs consectetur adipisci velit, sed quia non numquam eius.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box2">
                        <div class="box2_top">
                            <div class="box2_bot">
                                <div class="pad">
                                    <div class="wrapper">
                                        <figure class="left"><img src="images/marker_1.gif" alt=""></figure>
                                        <div class="cols">
                                            <a href="#">Quis autem vel eum iure reprehenderit qui</a>
                                            Darum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id maxime placeat facere possimus, omnis voluptas assumenda est.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box2">
                        <div class="box2_top">
                            <div class="box2_bot">
                                <div class="pad">
                                    <div class="wrapper">
                                        <figure class="left"><img src="images/marker_1.gif" alt=""></figure>
                                        <div class="cols">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing</a>
                                            Keque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consecte- tur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut<br>labore et dolore magnam.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
                <?php echo $this->render('sidebar.phtml');?>
            </div>
        </section>
    </div>
</div>