<div id="flash-container" style="width:740px; height:650px;">
    <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
            id="EuroFasad" width="740" height="650"
            codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab">
        <param name="movie" value="/flash/EuroFasad.swf" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#ffffff" />
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="lang" value="EN" />
        <embed src="/flash/EuroFasad.swf" quality="high" bgcolor="#ffffff"
               width="740" height="650" name="EuroFasad" align="middle"
               play="true" loop="false" quality="high" allowScriptAccess="sameDomain"
               type="application/x-shockwave-flash"
               pluginspage="http://www.macromedia.com/go/getflashplayer">
        </embed>
    </object>

</div>