<?php /*$this->headTitle()->append($this->translate('main-page')); */?>
<div class="wrapper">
    <div class="pad">
        <div class="wrapper"><h2><?php echo  $this->translate('menu-sofit'); ?></h2></div>
    </div>
    <div class="box pad_bot1 bot">
        <div class="pad marg_top">
            <img src="/assets/sofit1.jpg" /><br /><br />

        </div>
    </div>
    <h3>Преимущества софитов WELLTECH</h3>
    <div class="wrapper">
    				<ul class="banners">
    					<li>
    						<a href="#"><img src="assets/sof1.jpg" alt=""></a>
    						<div class="pad">
    							<p>Прост в содержании чистоты</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sof2.jpg" alt=""></a>
    						<div class="pad">
    							<p>Быстрый монтаж</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sof3.jpg" alt=""></a>
    						<div class="pad">
    							<p>Морозостойкий</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sof4.jpg" alt=""></a>
    						<div class="pad">
    							<p>Хорошая вентиляция</p>
    						</div>
    					</li>
    				</ul>
    			</div>

<h3>Цветовая гамма </h3>
    <div class="wrapper">
    				<ul class="banners">
    					<li>
    						<a href="#"><img src="assets/sf1.jpg" alt=""></a>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sf2.jpg" alt=""></a>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sf3.jpg" alt=""></a>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sf4.jpg" alt=""></a>
    					</li>
    				</ul>
    			</div>
    <h3>Комплектующие </h3>
    <img src="/assets/sofit2.jpg" />
    <img src="/assets/sofit3.jpg" />
    <img src="/assets/sofit4.jpg" />
    <img src="/assets/sofit5.jpg" />
    <img src="/assets/sofit6.jpg" />

</div>