<?php /*$this->headTitle()->append($this->translate('main-page')); */?>
<div class="wrapper">
    <div class="pad">
        <div class="wrapper"><h2><?php echo  $this->translate('menu-walls-panels'); ?></h2></div>
    </div>
    <div class="box pad_bot1 bot">
        <div class="pad marg_top">
            <img src="/assets/wp1.jpg" /><br /><br />

        </div>
    </div>
    <h3>Преимущества панелей ПВХ</h3>
    <div class="wrapper">
    				<ul class="banners">
    					<li>
    						<a href="#"><img src="assets/wp2.jpg" alt=""></a>
    						<div class="pad">
    							<p>Влагостойкость</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/wp3.jpg" alt=""></a>
    						<div class="pad">
    							<p>Быстрый монтаж</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/wp4.jpg" alt=""></a>
    						<div class="pad">
    							<p>Устойчивы к ультрафиолетовым лучам</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/wp5.jpg" alt=""></a>
    						<div class="pad">
    							<p>Эстетический вид</p>
    						</div>
    					</li>
    				</ul>
    			</div>

<h3>Цветовая гамма </h3>
    <img src="/assets/wp6.jpg" />
    <div class="wrapper">
    				<ul class="banners">
    					<li>
    						<a href="#"><img src="assets/wp7.jpg" alt=""></a>
    					</li>
    					<li>
    						<a href="#"><img src="assets/wp8.jpg" alt=""></a>
    					</li>
    					<li>
    						<a href="#"><img src="assets/wp9.jpg" alt=""></a>
    					</li>
    					<li>
    						<a href="#"><img src="assets/wp10.jpg" alt=""></a>
    					</li>
                        <li>
                   			<a href="#"><img src="assets/wp11.jpg" alt=""></a>
                   		</li>
                        <li>
                   			<a href="#"><img src="assets/wp12.jpg" alt=""></a>
                   		</li>
                        <li>
                            <a href="#"><img src="assets/wp13.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp14.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp15.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp16.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp17.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp18.jpg" alt=""></a>
                        </li>
                        <li>
                   			<a href="#"><img src="assets/wp19.jpg" alt=""></a>
                   		</li>
                        <li>
                   			<a href="#"><img src="assets/wp20.jpg" alt=""></a>
                   		</li>
                        <li>
                            <a href="#"><img src="assets/wp21.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp22.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp23.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp24.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp25.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp26.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp27.jpg" alt=""></a>
                        </li>
                        <li>
                            <a href="#"><img src="assets/wp28.jpg" alt=""></a>
                        </li>
    				</ul>
    			</div>

</div>