<?php /*$this->headTitle()->append($this->translate('main-page')); */?>
<div class="wrapper">
    <div class="pad">
        <div class="wrapper"><h2><?php echo  $this->translate('menu-siding'); ?></h2></div>
    </div>
<!--    <div class="box pad_bot1 bot">
        <div class="pad marg_top">
            <img src="/assets/siding1.png" /><br /><br />

        </div>
    </div>-->

    <img width="900" src="/assets/opl профиль.jpg" /><br /><br />
    <img width="900" src="/assets/oz водосток.jpg" /><br /><br />
    <img width="900" src="/assets/внутренний угол.jpg" /><br /><br />
    <img width="900" src="/assets/наружный угол.jpg" /><br /><br />
    <img width="900" src="/assets/околооконная планка.jpg" /><br /><br />
    <img width="900" src="/assets/панель стеновая 3.jpg" /><br /><br />
    <img width="900" src="/assets/панель стеновая.jpg" /><br /><br />
    <img width="900" src="/assets/соеденительный профиль.jpg" /><br /><br />
    <img width="900" src="/assets/стартовая планка.jpg" /><br /><br />
    <img width="900" src="/assets/фаска.jpg" /><br /><br />
    <img width="900" src="/assets/финишная планка.jpg" /><br /><br />
    <img width="900" src="/assets/Ф профиль корнизный.jpg" /><br /><br />

    <h3>Преимущества сайдингов WELLTECH</h3>
    <div class="wrapper">
    				<ul class="banners">
    					<li>
    						<a href="#"><img src="assets/sid1.jpg" alt=""></a>
    						<div class="pad">
    							<p>Прост в содержании чистоты</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sid2.jpg" alt=""></a>
    						<div class="pad">
    							<p>Быстрый монтаж</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sid3.jpg" alt=""></a>
    						<div class="pad">
    							<p>Морозостойкий</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sid4.jpg" alt=""></a>
    						<div class="pad">
    							<p>Эстетический вид</p>
    						</div>
    					</li>
    				</ul>
    			</div>

<h3>Цветовая гамма </h3>
    <div class="wrapper">
    				<ul class="banners banners2">
    					<li>
    						<a href="#"><img src="assets/sc1.jpg" alt=""></a>
    						<div class="pad">
    							<p>Белый</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sc2.jpg" alt=""></a>
    						<div class="pad">
    							<p>Бежевый</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sc3.jpg" alt=""></a>
    						<div class="pad">
    							<p>Кремовый</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/sc4.jpg" alt=""></a>
    						<div class="pad">
    							<p>Лимонный</p>
    						</div>
    					</li>
                        <li>
                            <a href="#"><img src="assets/sc5.jpg" alt=""></a>
                            <div class="pad">
                                <p>Розовый</p>
                            </div>
                        </li>
                        <li>
                            <a href="#"><img src="assets/sc6.jpg" alt=""></a>
                            <div class="pad">
                                <p>Салатный</p>
                            </div>
                   		</li>
                        <li>
                            <a href="#"><img src="assets/sc7.jpg" alt=""></a>
                            <div class="pad">
                                <p>Светло-серый</p>
                            </div>
                        </li>
    				</ul>
    			</div>
    <h3>Комплектующие </h3>
    <img src="/assets/siding2.jpg" /><br /><br />
    <img src="/assets/siding3.jpg" /><br /><br />
    <img src="/assets/siding4.jpg" /><br /><br />
    <img src="/assets/siding5.jpg" /><br /><br />
</div>