<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <![endif]-->
    <!--    <script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script>
  <script type="text/javascript" src="js/api.js"></script>-->
</head>
<body id="page1">
<div class="main">
    <!-- header -->
    <header>
        <div class="wrapper">
            <h1><a href="/" id="logo">Smart Biz</a></h1>
            <div id="locale">
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'ro_MD'), 'default', true); ?>">
                    <img src="/images/locale/ro_MD.png" />
                </a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'ru_RU'), 'default', true); ?>">
                    <img src="/images/locale/ru_RU.png" />
                </a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'en_US'), 'default', true); ?>">
                    <img src="/images/locale/en_US.png" />
                </a>

            </div>
        </div>
        <div class="wrapper">
            <!--            <div class="text">
                <span class="text1">Effective<span>business solutions</span></span>
                <a href="#" class="button">read more</a>
            </div>-->
            <div class="slider-wrapper theme-default">
                <div class="ribbon"></div>
                <div id="slider" class="nivoSlider">
                    <img src="images/Untitled.jpg" alt="" />
                    <img src="images/Untitled1.jpg" alt="" />
                </div>
            </div>
        </div>
        <!--        <nav>
            <ul id="menu">
                <li class="alpha" id="menu_active"><a href="index.html"><span><span>Home</span></span></a></li>
                <li><a href="About.html"><span><span>About</span></span> </a></li>
                <li><a href="Projects.html"><span><span>Projects</span></span></a></li>
                <li><a href="Contacts.html"><span><span>Contacts</span></span></a></li>
                <li class="omega"><a href="Sitemap.html"><span><span>Sitemap</span></span></a></li>
            </ul>
        </nav>-->
        <!-- Menu structure example -->
        <div id="myMenu" class="nfPure nfMain" style="width:920px;">

            <div class="nfItem"><h2><a class="nfLink" href="/"><span id="gn_home"><?php echo  $this->translate('menu-home'); ?></span></a></h2></div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_facade"><?php echo  $this->translate('menu-facade'); ?></span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="/siding"><?php echo  $this->translate('menu-siding'); ?></a></li>
                    <li class="nfItem"><a class="nfLink" href="/sofit"><?php echo  $this->translate('menu-sofit'); ?></a></li>
                    <li class="nfItem"><a class="nfLink" href="/siding-color-chooser"><?php echo  $this->translate('menu-siding-color-chooser'); ?></a></li>
                </div>
            </div>


            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_walls"><?php echo  $this->translate('menu-walls-roofs'); ?></span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="/walls-accessory"><?php echo  $this->translate('menu-walls-accessory'); ?></a></li>
                    <li class="nfItem"><a class="nfLink" href="/walls-panels"><?php echo  $this->translate('menu-walls-panels'); ?></a></li>
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_windows"><?php echo  $this->translate('menu-windows'); ?></span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="/window"><?php echo  $this->translate('menu-window'); ?></a></li>
                    <li class="nfItem"><a class="nfLink" href="/window-ebb"><?php echo  $this->translate('menu-ebb'); ?></a></li>
                </ul>
                </div>
            </div>
            <!--pipes-pvs means cerepita-->
            <div class="nfItem"><h2><a class="nfLink" href="/pipes-pvs"><span id="gn_pipes"><?php echo  $this->translate('menu-pipes-pvs'); ?></span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <!--                    <li class="nfItem"><a class="nfLink" href="/pipes-accessory"><?php /*echo  $this->translate('menu-pipes-accessory'); */?></a></li>
                    <li class="nfItem"><a class="nfLink" href="/pipes-pvs"><?php /*echo  $this->translate('menu-pipes-pvs'); */?></a></li>-->
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_prices"><?php echo  $this->translate('menu-prices'); ?></span></a></h2></div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_company"><?php echo  $this->translate('menu-company'); ?></span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="/about"><?php echo  $this->translate('menu-about-company'); ?></a></li>
                    <!--<li class="nfItem"><a class="nfLink" href="#"><?php /*echo  $this->translate('menu-market-outlet'); */?></a></li>-->
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="/contact"><span id="gn_phones"><?php echo  $this->translate('menu-contact'); ?></span></a></h2></div>

        </div>
    </header>
    <!-- / header -->
    <!-- content -->
    <section id="content">
        <?php echo $this->layout()->content ?>
    </section>
    <!-- / content -->
    <!-- footer -->
    <footer>
        <a href="/">&copy; Fasade.md <?php echo date('Y'); ?></a><br />
    </footer>
    <!-- / footer -->
</div>
<script type="text/javascript"> Cufon.now(); </script>
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>

<!--Create a new menu object and activate it (place this script after the structure or attach to an onload type event)-->
<script type="text/javascript">


    //Menu configuration properties (hide and show timers in Milliseconds)
    var config = {showTimerMS:250,hideTimerMS:250,stickyHover:true};

    //Pass the menu object construcor an ID or object representing the root node of your structure
    var myMenu = new NF.widget.menu("myMenu", config);

    //set the default delay timer for the menus playerSynchronizer animations
    NF.anim.playerSynchronizer.delay = 15;


    /*~~~~~~~~ Hover Effect - Level 1~~~~~~~~~~~~~*/
    var hovClip = new NF.anim.clip({backgroundColor:{start:"#000000",end:"#990101"}},{frames:5,hook:"NFplayOnLinkHoverShow"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",widgetLevel:"level==1"}));

    hovClip = new NF.anim.clip({backgroundColor:{start:"#990101",end:"#000000"}},{frames:40,hook:"NFplayOnLinkHoverHide"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",widgetLevel:"level==1"}));


    /*~~~~~~~~ Hover Effect - Level 2~~~~~~~~~~~~~*/
    var hovClip = new NF.anim.clip({backgroundColor:{start:"#222222",end:"#990101"}},{frames:5,reset:true,hook:"NFplayOnLinkHoverShow"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",widgetLevel:"level==2"}));

    hovClip = new NF.anim.clip({backgroundColor:{start:"#990101",end:"#222222"}},{frames:40,reset:true,hook:"NFplayOnLinkHoverHide"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",excludeClass:"nfParentLink",widgetLevel:"level==2"}));


    /*~~~~~~~~ Show Subs Effect - Lev 1 ~~~~~~~~~~~~~*/
    var clip = new NF.anim.clip({opacity:{start:0, end:1}}, {frames:10,reset:true,hook:"NFplayOnSubShow"});
    var subAnim_Show_Replicator = new NF.replicator("transition", {master:clip,widgetClass:"nfSubC",widgetLevel:'level==1'});
    myMenu.addReplicator(subAnim_Show_Replicator);


    /*~~~~~~~~ Hide Subs Effect - Lev 1 ~~~~~~~~~~~~~*/
    clip = new NF.anim.clip({opacity:{start:1, end:0}}, {frames:10,reset:true,hook:"NFplayOnSubHide"});
    var subAnim_Hide_Replicator = new NF.replicator("transition", {master:clip,widgetClass:"nfSubC",widgetLevel:'level==1'});
    myMenu.addReplicator(subAnim_Hide_Replicator);


    /*~~~~~~~~ Show Subs Effect - Lev 2+ ~~~~~~~~~~~~~*/
    var clip1 = new NF.anim.clip({opacity:{start:0, end:1}}, {frames:10,reset:true,hook:"NFplayOnSubShow"});
    var clip2 = new NF.anim.clip({clip:{start:{value:'0% 0% 0% 0%', refNode:"self"}, end:{value:'0% 100% 100% 0%', refNode:"self"}}}, {frames:12,reset:true,hook:"NFplayOnSubShow"});
    var timeline = new NF.anim.timeline(clip1,'NFplayOnSubShow');
    timeline.addTrack(clip2);
    var subAnim_Show_Replicator = new NF.replicator("transition", {master:timeline,widgetClass:"nfSubC",widgetLevel:'level>1'});
    myMenu.addReplicator(subAnim_Show_Replicator);


    /*~~~~~~~~ Hide Subs Effect - Lev 2+ ~~~~~~~~~~~~~*/
    clip1 = new NF.anim.clip({opacity:{start:1, end:0}}, {frames:10,reset:true,hook:"NFplayOnSubHide"});
    clip2 = new NF.anim.clip({clip:{start:{value:'0% 100% 100% 0%', refNode:"self"}, end:{value:'0% 0% 0% 0%', refNode:"self"}}}, {frames:12,reset:true,hook:"NFplayOnSubHide"});
    timeline = new NF.anim.timeline(clip1,'NFplayOnSubHide');
    timeline.addTrack(clip2);
    var subAnim_Hide_Replicator = new NF.replicator("transition", {master:timeline,widgetClass:"nfSubC",widgetLevel:'level>1'});
    myMenu.addReplicator(subAnim_Hide_Replicator);


    //Activate the menu
    myMenu.activate();




</script>
</body>
</html>