<article class="col1 pad_left1">
    <h2>Advantages</h2>
    <ul class="list2">
        <li><a href="#"><img src="images/icon1.jpg" alt="">Starting up</a></li>
        <li><a href="#"><img src="images/icon2.jpg" alt="">Finance and grants</a></li>
        <li><a href="#"><img src="images/icon3.jpg" alt="">Taxes, returns &amp; payroll</a></li>
        <li><a href="#"><img src="images/icon4.jpg" alt="">Employment &amp; skills</a></li>
        <li class="bg_none"><a href="#"><img src="images/icon5.jpg" alt="">Health, safety, premises</a></li>
    </ul>
    <div class="box1"><div class="box1_bot"><div class="box1_top">
        <div class="pad">
            <h2>Newsletter</h2>
            Sign up for weekly newsletter:
            <form id="sign_up" method="post">
                <div>
                    <input type="text" class="input">
                    <a href="#" onClick="document.getElementById('sign_up').submit()">Sign up</a>
                </div>
            </form>
        </div>
    </div></div></div>
</article>