<div class="body5">
    <div class="body6">
        <div class="main">
            <div class="wrapper">
                <figure class="left"><img src="images/letter4.png" alt=""></figure>
                <h2>Browse The Ultimate <span>List Of Products</span>!</h2>
                Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam.
            </div>
        </div>
    </div>
</div>
<div class="body7">
    <div class="main">
        <section id="content">
            <div class="wrapper">
                <article class="col2">
                    <div class="pad1">
                        <h2>Our Products</h2>
                        <p class="pad_bot2">Sed quia consequuntur magni dolores eosqui ratione voluptatem sequi nes ciunt neque porro quisiquam est, qui dolorem ipsum quia doloirs consectetur adipisci velit, sed quia non numquam eiusquidem rerum facilis:</p>
                        <div class="wrapper line1 marg_bot1">
                            <ul class="col1 list1">
                                <li><a href="#">Sed ut perspiciatis unde omnis</a></li>
                                <li><a href="#">Accusantium doloremque laudantium</a></li>
                                <li><a href="#">Aperiam eaque ipsa quae</a></li>
                                <li><a href="#">Beatae vitae dicta explicabo minima</a></li>
                                <li><a href="#">Nemo enim ipsam voluptatem</a></li>
                            </ul>
                            <ul class="list1 pad_left1 left">
                                <li><a href="#">Neque porro quisquam est qui</a></li>
                                <li><a href="#">Dolorem ipsum quia dolor sit amet</a></li>
                                <li><a href="#">Consectetur, adipisci velit</a></li>
                                <li><a href="#">Numquam emodi tempora incidnt</a></li>
                                <li><a href="#">Magnam aliquam quaerat</a></li>
                            </ul>
                        </div>
                        At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.
                    </div>
                </article>
                <?php echo $this->render('sidebar.phtml');?>
            </div>
        </section>
    </div>
</div>