<?php /*$this->headTitle()->append($this->translate('main-page')); */?>
<div class="wrapper">
    <div class="pad">
        <div class="wrapper"><h2><?php echo  $this->translate('menu-pipes-accessory'); ?></h2></div>
    </div>
    <div class="box pad_bot1 bot">
        <div class="pad marg_top">
            <img src="/assets/pa1.jpg" /><br />
            <img src="/assets/pa2.jpg" />

        </div>
    </div>

</div>