<?php /*$this->headTitle()->append($this->translate('main-page')); */?>
<div class="wrapper">
    <div class="pad">
        <div class="wrapper"><h2><?php echo  $this->translate('menu-window'); ?></h2></div>
    </div>
    <div class="box pad_bot1 bot">
        <div class="pad marg_top">
            <img src="/assets/w1.jpg" /><br />
            <p>Внутренние и наружные подоконники WELLTECH прочны, устойчивы к солнечным лучам, эстетичные, трудновоспламеняемые, а также легки и просты в монтаже, устойчивы к коррозии и не требуют  специальной обработки во время эксплуатации, устойчивы к механическим повреждениям.</p>

        </div>
    </div>
    <h3>ПРЕИМУЩЕСТВА ПОДОКОННИКОВ WELLTECH</h3>
    <div class="wrapper">
    				<ul class="banners">
    					<li>
    						<a href="#"><img src="assets/w2.jpg" alt=""></a>
    						<div class="pad">
    							<p>Герметичные и звукоизолирующие</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/w3.jpg" alt=""></a>
    						<div class="pad">
    							<p>Устойчивы к ультрафиолетовым лучам</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/w4.jpg" alt=""></a>
    						<div class="pad">
    							<p>Устойчивы к механическим повреждениям</p>
    						</div>
    					</li>
    					<li>
    						<a href="#"><img src="assets/w5.jpg" alt=""></a>
    						<div class="pad">
    							<p>Просты в содержании чистоты</p>
    						</div>
    					</li>
    				</ul>
    			</div>

    <img src="/assets/w6.jpg" />
    <img src="/assets/w7.jpg" />

</div>